### ISSUE TITLE
animint2 goals

### ISSUE THREAD

**Issue by faizan-khan-iit** [tdhock/animint2#2]
Discuss the major changes in `animint2`. Outline here: https://github.com/rstats-gsoc/gsoc2017/wiki/Animated-interactive-plots-(animint)#ideas-for-gsoc-2017-coding-projects

- [x] Remove `ggplot2` dependecy
- [ ] Object oriented internals: geom specific code separated from geom independent code
- [x] Change syntax: use params instead of `clickSelects`/`showSelected`/etc aesthetics
- [ ] Introduce dependency on `data.table` to handle larger datasets
- [ ] `htmlwidgets`/`crosstalk` support

This list is in decreasing order of priority.

**Comment by faizan-khan-iit** [comment]
For removing the dependency on ggplot2, we will need to make these changes:
1. Copy over all geom code, including `ggproto`, and make changes to avoid warnings
2. Write animint versions of ggplot2 functions including `plot_theme` and `ggplot_build` used in the code
3. Copy over other functions used in animint code as is

**Comment by faizan-khan-iit** [comment]
@tdhock Would you like to add anything to this? I think this should remove the dependency altogether

**Comment by tdhock** [comment]
that sounds good to me, but I would say that data.table and syntax change are more important than htmlwidgets/crosstalk

**Comment by faizan-khan-iit** [comment]
@tdhock About removing the dependency on `ggplot2` and I think it's not really necessary. Here is an alternative:
1. Instead of copying over the geoms and editing them, we could make `geom_*_animint()` versions of them in our code like you suggested. We can edit the definitions to include all the required params in `animint`
2. Like before, we could create our own versions: `animint::ggplot_build`, `animint::plot_theme` etc, wherever needed
3. We can just keep using the exported functions from `ggplot2` that work fine and present no problems.

I suggest this because:
1. If any minor bugs get fixed in `ggplot2`, we won't have to keep track of them
2. This will help keep up code-base cleaner
3. This seems more natural to me, since we will have most of the freedom
4. We can always just copy over the code in the future if required
5. It is less work with same results

**Comment by tdhock** [comment]
that sounds ok in theory. if you can get that to work, great!

**Comment by faizan-khan-iit** [comment]
@tdhock Should we start working on `data.table` next? I guess that we will have to profile the code first to see where we should dedicate our efforts.

**Comment by tdhock** [comment]
right, if you want to work on optimizing the speed using the data.table,
the first thing to try would be a code profiler to see which functions to
focus on. My guess would be that most of the time is spent in splitting the
files, and for loops over the different subsets (e.g. saving tsv files --
something that probably could be sped up using data.table::fwrite instead
of write.table)

**Comment by faizan-khan-iit** [comment]
Opened #8 for `data.table`
