### ISSUE TITLE
Handling geoms in animint2

### ISSUE THREAD

**Issue by faizan-khan-iit** [tdhock/animint2#3]
To remove the warnings and dependencies on un-exported `ggplot2` functions we need to create our own versions of `geom_*()` functions, [as discussed here.](https://github.com/tdhock/animint2/issues/2#issuecomment-288871082)

So I created the `geom_point_animint()` which inherits directly from `geom_point()` and adds the aesthetics `showSelected`, `clickSelects` etc : https://github.com/faizan-khan-iit/animint2/commit/abf689e407d5fe5ffb5e4a54470405459e26f82e

Here are the examples for the code:
Using `showSelected` aesthetic: http://bl.ocks.org/faizan-khan-iit/raw/9704a276923429786990e32985f5ed18/
Using `colour` aesthetic: https://bl.ocks.org/faizan-khan-iit/raw/529d401ab85c4215c2daf0beba493771/

The code for the examples:
```
mtcars$cyl <- as.factor(mtcars$cyl)

p <- ggplot() + geom_point_animint(aes(x=hp,
                                       y=disp,
                                       showSelected=cyl),
                                   data = mtcars)
animint2::animint2dir(list(p=p), "~/test_v1")

p2 <- ggplot() + geom_point_animint(aes(x=hp,
                                        y=disp,
                                        colour=cyl),
                                    data = mtcars)
animint2::animint2dir(list(p=p2), "~/test_v2")

```

**Comment by faizan-khan-iit** [comment]
The current code will *not* work for ggplot2 v2.2.1 because they have made various changes to the facet code: https://blog.rstudio.org/2016/11/14/ggplot2-2-2-0/

However it works with the CRAN version 2.1.0, so there should be no problems once we get the facet system working.

**Comment by tdhock** [comment]
Hey @faizan-khan-iit  I see that in this approach `showSelected` works as an aes? What about `showSelected2` etc?

I think it would be preferable to change the syntax to params rather than aesthetics: `geom_point(aes(x=hp, y=disp), showSelected="cyl")` -- would that be possible in this new approach?

**Comment by faizan-khan-iit** [comment]
@tdhock I will have to look into how to handle the multiple `showSelected` params.

In the meantime could you please drop a little note here about the `getStrips` and related functions in `facets.R`? We will have to edit that code so a little overview of what they do would be a great help..

**Comment by tdhock** [comment]
I think that the facets.R code is mostly just a copy-paste from ggplot2. We may be able to delete that code if we are just going to re-do the computations of scales for each facet ourselves (the computations will be different from standard ggplot2, because of showSelected).

**Comment by faizan-khan-iit** [comment]
I was trying to get the new syntax working with `GeomAnimint`, but it has just been error after error yet. So I tried another way to handle showSelected in our code: https://github.com/faizan-khan-iit/animint2/commit/3118c1ce8f8a73b9f204884e1acf683c09b9278c

With this we will have this as our Geom*Animint code (just a kind of wrapper on the original ggplot2 code with additional params): https://github.com/faizan-khan-iit/animint2/blob/master/R/geom_point_animint.R

Here are some use cases:
```
## Case 1: Works okay
mtcars$cyl <- as.factor(mtcars$cyl)

p1 <- ggplot() + geom_point_animint(aes(x=hp,
                                       y=disp),
                                   showSelected=list(c("cyl", "am")),
                                   # I have to pass the showSelected values like this
                                   # because ggplot2 does not allow random number of values in params
                                   # Either 1 of equal to length of data 
                                   data = mtcars)
animint2::animint2dir(list(p=p1), "~/test_v1")

## Case 2: Gives a warning (for now)
p2 <- ggplot() + geom_point_animint(aes(x=hp,
                                        y=disp,
                                        showSelected=cyl),
                                    data = mtcars)
animint2::animint2dir(list(p=p2), "~/test_v2")
```
The warning:
```
In animint2::animint2dir(list(p = p2), "~/test_v2") :
  Please use showSelected as a parameter. Use of showSelected as an aesthetic has been depriciated.
```

**Comment by faizan-khan-iit** [comment]
@tdhock I would like some feedback on two things:
1. Is this okay as an approach? We basically will have to create shell `geom_*_animint` functions over the existing ggplot2 geoms with minimal changes, so that is a plus.
2. How should the `colour` value be passed when we add `showSelected`? Should we only add it when it is passed in as an `aes`, like we do currently?

I will try and see if the `GeomAnimint` approach can be used, since I still prefer that over this approach.

**Comment by tdhock** [comment]
Thanks for investigating the feasibility of showSelected params using ggplot2.

From Case 1 it is nice that it is working, but it is definitely sub-optimal to require the user to write `showSelected=list(c("cyl", "am"))`. One way to get around would be to allow `showSelected=c("cyl", "am")` and then modify the definition of geom_point_animint. Add explicit showSelected parameter so that the showSelected argument does not end up in the dots (...). Then make sure that showSelected is a character vector, and call ggplot2::layer(params=list(showSelected=list(showSelected))).

On the other hand this makes me think we should just remove the ggplot2 dependency and modify their code for our purposes.

For case 2 I suggest that we stop with an error (rather than the current deprecation warning). Now that we are moving to the new animint2 package, we don't need to allow backwards-compatibility.

Also I wonder about the names of the functions. `geom_point_animint` or `ageom_point` or `geoma_point`?

For your second question about `colour` values, I did not understand. Can you please clarify / re-state your question in a different way?

Too bad GeomAnimint is not working -- to me this suggests that we should drop ggplot2 dependency and write the code in the way that makes sense for us.

**Comment by faizan-khan-iit** [comment]
Here are the changes: https://github.com/faizan-khan-iit/animint2/commit/1dacc7e56e667f4f4df73937cf713ec7fb08ff03

With these changes:
1. Case 1 works fine
2. Case 2 gives error in the `ggplot2` evaluation itself, when `showSelected` is not a param. So we need to sort that out. So some code like:
```
p <- ggplot() + geom_point_animint(aes(x=hp, y=disp), data = mtcars)
```

also gives the error:

```
Error in ggplot2::layer(data = data, mapping = mapping, stat = stat, geom = GeomPointAnimint,  : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```

I think both `geom_point_animint` (or `geom_point_a`) and `geoma_point` are fine. We could use either.

For the second question I just wanted to inquire since we have changed the syntax for the `showSelected`, and we add showSelected when we specify `colour` as an aesthetic, for e.g.:

```
p <- ggplot() + geom_point_animint(aes(x=hp, y=disp, colour=cyl), data = mtcars)
```
will automatically add a showSelected aesthetic for `cyl`. So do we need to change something
here or is it fine?

**Comment by faizan-khan-iit** [comment]
Found a great way to pass the animint specific params in new `geom_*` functions: https://github.com/faizan-khan-iit/animint2/commit/04bf2686f96baa6e70a8594d6964b02d3ffee0ca

I was digging through various geom definitions to solve the above problem when I came across [this](https://github.com/tidyverse/ggplot2/blob/master/R/geom-bar.r#L125-L128). It allows to pass an argument that is not an aesthetic without raising warnings.

The [new definition of `geom_point_animint`](https://github.com/faizan-khan-iit/animint2/blob/04bf2686f96baa6e70a8594d6964b02d3ffee0ca/R/geom_point_animint.R) uses this to pass all the animint specific parameters as a single parameter list: `animnitParams`.

Here are some examples:

```
mtcars$cyl <- as.factor(mtcars$cyl)


## 1. No error. But plot not rendered yet. Working on it
animintParams <- list(showSelected=c("cyl", "am"),
                     clickSelects = c("am"))
p1 <- ggplot() + geom_point_animint(aes(x=hp,
                                       y=disp),
                                   animintParams = animintParams,
                                   data = mtcars)
animint2::animint2dir(list(p=p1), "~/test_v1")

##  2. No error. But plot not rendered yet. Working on it
p2 <- ggplot() + geom_point_animint(aes(x=hp,
                                        y=disp),
                                    animintParams = list(showSelected=c("cyl")),
                                    data = mtcars)
animint2::animint2dir(list(p=p2), "~/test_v2")

##  3. Produces same error as before
p3 <- ggplot() + geom_point_animint(aes(x=hp,
                                        y=disp,
                                        showSelected=cyl),
                                    data = mtcars)
animint2::animint2dir(list(p=p3), "~/test_v3")

##  4. No error. Works well
p4 <- ggplot() + geom_point_animint(aes(x=hp,
                                        y=disp),
                                    data = mtcars)
animint2::animint2dir(list(p=p4), "~/test_v4")
```

All the animint specific params are stored in one place as a named list in `L$geom_params$animintParams`. I think this is a great way to handle this because we have all our required params, the syntax is intuitive (especially example 1), and it will use minimal additions and won't clutter up our code.

@tdhock What do you think?

**Comment by tdhock** [comment]
thanks for figuring out that hack. any idea if it is officially supported by ggplot2 or if we will have compatibility problems in the future?

I keep getting the feeling that by dropping the ggplot2 dependency, we will have fewer maintenance problems in the future. For you what are the advantages to keeping the ggplot2 dependency?

nice to know the animintParams syntax is possible. the `geom_point_animint(showSelected=c("cyl", "am"), clickSelects="smoething")` syntax is still preferable though (instead of making the plot designer write animintParams expliticly). We could edit the arguments of `geom_point_animint` to achieve that.

**Comment by faizan-khan-iit** [comment]
I think the primary advantage would be that we will not have too much code to handle (ggplot2 has a lot of code), and we will not have to handle the bug fixes in the ggplot2 code ourselves in the future as I mentioned in [this comment](https://github.com/tdhock/animint2/issues/2#issuecomment-288871082)

Also regarding the `animintParams` syntax, I used this because this hack allows us to pass only one additional parameter. Or more appropriately, I do not really understand how this works yet, so I can only pass a single extra parameter. But I think the `animintParams` syntax is fine too, if you agree.

Lastly, any comments on the `colour` aesthetic?

**Comment by tdhock** [comment]
for me the main advantage for keeping the ggplot2 dependency is that we get automatic non-interactive rendering, which can be useful for debugging.

about having not much code to handle, I think that will be solved if we adopt the object-oriented programming approach of the ggplot2 package (copy ggproto to our own version, aproto).

for me it seems like there are many more disadvantages to keeping the ggplot2 dep.

- there is not much ggplot2 code that we will use to compile animints (we are not going to use ggplot2::ggplot_build etc anymore).
- the code that we will use is related to defining the ggplots/geoms, and by keeping the ggplot2 dependency we are keep their constraints, which are often irrelevant in our context. e.g. params must be either 1 or length of the data.
- maintenance problems in the future when ggplot2 is updated with backwards-incompatible changes.

in the end this is your GSOC project so I will let you make the final decision.

about the hack only allowing one parameter, it seems to me that if you add more arguments to the draw_panel function, they should all be useable as params. IMO it is OK to use animintParams inside ggplot2::layer but not as an argument of geom_ functions -- we should allow the designer to directly specify showSelected/clickSelects/chunk_vars as arguments of geom_ functions.

about the colour aesthetic. in old animint we made a showSelectedColour aesthetic. In animint2 we should instead add an element to the showSelected vector. e.g. for `geom_point(aes(foo, bar, color=baz), showSelected=c("var1", "var2"))` the compiler should recognize the color aesthetic and add add an element to the showSelected vector, `c("var1", "var2", "baz")`. Also in my experience sometimes this is behavior is unwanted, so it should be configurable via `theme_animint(auto_showSelected=c("fill", "linetype"))` meaning that only the fill and linetype aesthetics should be used to generate automatic showSelected variables -- not colour. By default auto_showSelected should be all aesthetics which would generate a legend.

**Comment by faizan-khan-iit** [comment]
I guess the pros to removing the dependency outweigh the cons here. However I still think all that code will be a major addition to our package. But if it makes further maintenance easier, I think it will be worth the effort. Especially since not removing the dependency also seems to be a bit complicated.

Regarding this approach, should I first copy over all the code from ggplot2 and then skim away the unnecessary code?

**Comment by tdhock** [comment]
sure, that sounds reasonable.
