### ISSUE TITLE
update margin() function ?

### ISSUE THREAD

**Issue by pmur002** [tdhock/animint2#31]
Hi  
Thomas Lin Pedersen and I are working on some speed ups to 'grid' units [https://github.com/thomasp85/grid/issues/14], which involve a new unit implementation.
During testing, we found that 'animint2' fails because its margin() function creates its own "unit" objects (that are incompatible with the new unit implementation).
The ggplot2::margin() function has been updated for the new unit implementation - would you consider updating animint2::margin() to match ?  (I assume that is the necessary development path, given that you appear to be avoiding a 'ggplot2' dependency[?]).
Paul

**Comment by tdhock** [comment]
hi @pmur002 can you please describe in more detail what exactly is changing/breaking and what we would need to do to fix it? I can try to find a student to work on it.

**Comment by pmur002** [comment]
I will try :)

Thomas and I are working on changing the internal implementation of 'grid' units (and want to commit this to r-devel soon).

Those changes broke a previous version of 'ggplot2', so 'ggplot2' has been fixed in a new version (on CRAN).

'animint2' has copies (forks) of lots of 'ggplot2' functions, but it has copies from the old version of 'ggplot2'.

This means that 'animint2' will break (just like the old 'ggplot2' broke) when we commit the 'grid' changes  to r-devel.   A specific example that we have identified is the `ggplot2::margin()` function (which used to peek at 'grid' unit internals in the old 'ggplot2' version), though that is unlikely to be the only example.

The ultimate solution is to update 'animint2' to the new version of 'gpplot2'.  You might be able to get away with just updating specific functions (e.g., `ggplot2::margin()`) but that seems like a terrible idea to me.  Hopefully you can use `git merge` et al to do the heavy lifting (?)

Here is the R CMD check error that I get with our modified 'grid' ...

```
* checking examples ... ERROR
Running examples in ‘animint2-Ex.R’ failed
The error most likely occurred in:

> ### Name: guide_colourbar
> ### Title: Continuous colour bar guide.
> ### Aliases: guide_colourbar guide_colorbar
> 
> ### ** Examples
> 
> df <- reshape2::melt(outer(1:4, 1:4), varnames = c("X1", "X2"))
> 
> p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
> p2 <- p1 + geom_point(aes(size = value))
> 
> # Basic form
> p1 + scale_fill_continuous(guide = "colorbar")
> p1 + scale_fill_continuous(guide = guide_colorbar())
> p1 + guides(fill = guide_colorbar())
> 
> # Control styles
> 
> # bar size
> p1 + guides(fill = guide_colorbar(barwidth = 0.5, barheight = 10))
> 
> # no label
> p1 + guides(fill = guide_colorbar(label = FALSE))
> 
> # no tick marks
> p1 + guides(fill = guide_colorbar(ticks = FALSE))
> 
> # label position
> p1 + guides(fill = guide_colorbar(label.position = "left"))
> 
> # label theme
> p1 + guides(fill = guide_colorbar(label.theme = element_text(colour = "blue", 
angle = 0)))
> 
> # small number of bins
> p1 + guides(fill = guide_colorbar(nbin = 3))
> 
> # large number of bins
> p1 + guides(fill = guide_colorbar(nbin = 100))
> 
> # make top- and bottom-most ticks invisible
> p1 + scale_fill_continuous(limits = c(0,20), breaks = c(0, 5, 10, 15, 20),
+  guide = guide_colorbar(nbin=100, draw.ulim = FALSE, draw.llim = FALSE))
> 
> # guides can be controlled independently
> p2 +
+   scale_fill_continuous(guide = "colorbar") +
+   scale_size(guide = "legend")
Error in `attributes<-`(x, attr) : 
  'names' attribute [2] must be the same length as the vector [1]
Calls: <Anonymous> ... gtable_add_rows -> insert.unit -> unit.c -> [ -> [.unit
Execution halted
```
To get that result yourself (and to test any fixes), you might need a patched version of r-devel (patched using Thomas' 'grid' fork [https://github.com/thomasp85/grid/tree/new-unit]).  

Alternatively, you could create an 'animint2' branch for making your changes that I can clone and test on my setup.

I am typing @thomasp85 in the hopes that this will make the discussion visible to Thomas (and in the hope that he might have other useful information and/or suggestions).

**Comment by tdhock** [comment]
hi, thanks for the suggestion to use `git merge` to get the recent versions from ggplot2. even better would be if we did not have to fork ggplot2 in the first place. but animint2 needed some changes that the ggplot2 devs did not want to support, so here we are. and so I don't think it will be feasible to use git merge. Instead it would be helpful to know how ggplot2 was changed to accomodate these new grid news. I see that the tidyverse/ggplot2 now has
```r
margin <- function(t = 0, r = 0, b = 0, l = 0, unit = "pt") {
  u <- unit(c(t, r, b, l), unit)
  class(u) <- c("margin", class(u))
  u
}
```
whereas animint2 now has
```r
margin <- function(t = 0, r = 0, b = 0, l = 0, unit = "pt") {
  structure(unit(c(t, r, b, l), unit), class = c("margin", "unit"))
}
```
so the only difference  I see is class(u) instead of "unit" so is that the only fix that needs to happen?

**Comment by pmur002** [comment]
I think "the only fix" would be a bold claim, but that is certainly one fix that needs to happen.  You could try it and see.  The 'grid' new unit change is about to go into r-devel, so you should be able to test against that soon.

Even if 'git merge' does not work, perhaps 'git diff' would still be useful to check for any other significant differences between your fork and ggplot2 (?)

**Comment by tdhock** [comment]
this seems to be fixed by @lazycipher 's PR, thanks!
