### ISSUE TITLE
Unavailable on CRAN?

### ISSUE THREAD

**Issue by danudwary** [tdhock/animint2#36]
Is this software no longer available? Deprecated? Is there a recommended replacement?

> Package ‘animint2’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the archive.
> 
> Archived on 2020-03-29 as requested by the maintainer.
> 
> Please use the canonical form https://CRAN.R-project.org/package=animint2 to link to this page.

**Comment by tdhock** [comment]
there are some problems with R-4.0 compatibility that @lazycipher  plans to work out during GSOC, so hopefully animint2 will be back on CRAN by the end of summer.
A work-around  is to use a previous version of R and install animint2 from github.
