### ISSUE TITLE
Issues with testing

### ISSUE THREAD

**Issue by lazycipher** [tdhock/animint2#37]
I was trying to run the tests on my system but I'm getting certain errors.
### How errors show up?
Cloned repo, installed needed version of RSelenium(1.3.5).
Loaded needed libraries and helper files.
```
library("testthat")
library("animint2")
library("RSelenium");library("XML")
source("helper-functions.R")
source("helper-HTML.R")
source("helper-plot-data.r")
```
Initialized test with `tests_init()` for headless at first and `tests_init("firefox")` for firefox.
Used `tests_run(filter="renderer")` to run phantomjs. [Console Output](https://paste.ubuntu.com/p/yXkGpvZNvj/). PhantomJS crashed everytime I ran the test.

Then I initialized tests to run with firefox and see what it looks like on a GUI and it looked and it seems the $clickElement function not working as it didn't show any effect and many more errors.
Here's the output of the test run on firefox. [Console Output](https://paste.ubuntu.com/p/SmwmxYN68Y/)

One more thing was the availability of needed `.Rmd` file in [Knit Print test](https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/tests/testthat/test-renderer1-knit-print.R#L5).
I kept getting this error when I tried running the test but in order to make it work, I had to hard code that to get from the project repo. [Error Console Output](https://paste.ubuntu.com/p/48Bygx7txg/)
I made these changes to make it work:
- replaced this [Code](https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/tests/testthat/test-renderer1-knit-print.R#L5)
with this code: `Rmd.file <- "../../inst/examples/test_knit_print.Rmd"`

**Comment by tdhock** [comment]
that is really strange that some tests are passing and others are not, but I guess that makes sense as you are upgrading to much newer versions of the testing software (RSelenium etc).
- So the clickElement function is not working at all any time in any tests? Or is it in just some tests?
- can you upgrade to the most recent version of RSelenium please? looks like 1.7.7 on https://cran.r-project.org/web/packages/RSelenium/index.html
- Knit Print test should work without modification if you install the package, the file is here https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/inst/examples/test_knit_print.Rmd (the animint2/inst/examples directory in the source package should be copied to animint2/examples at the location where the package is installed)
-

**Comment by lazycipher** [comment]
As of now, I'm using the specified version of RSelenium(1.3.5) and Phantomjs(1.9.8).
- Looks like the `clickElement()` function worked in a different test but the way it was used was different. [`test-renderer1-knit-print.R`](https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/tests/testthat/test-renderer1-knit-print.R#L105) didn't work but [`test-renderer2-widerect.R`](https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/tests/testthat/test-renderer2-widerect.R#L311) worked.
- I'll check and update here after upgrading the version or RSelenium.
- The directory structure after installation of animint2 looks like this as of now. There isn't any /examples or /inst/examples directory after installation of animint2. Even I reinstalled and checked.
`/home/lazycipher/R/x86_64-pc-linux-gnu-library/3.6/animint2/`
![Screenshot from 2020-05-15 12-25-44](https://user-images.githubusercontent.com/17141301/82022078-a92a9100-96a9-11ea-96d3-48a50491e472.png)

Let me just upgrade RSel to the latest version and make it work and see if tests pass or what happens.

**Comment by tdhock** [comment]
hi that is good that most of the test are working now, but please try to upgrade to most recent versions of RSelenium / selenium. we need to get that working soon.
also what version of R are you using?
please try using R-4.0.0 with this branch https://github.com/tdhock/animint2/pull/34 which impements that implements some fixes for R-4.0

**Comment by lazycipher** [comment]
I've upgraded the packages. There are some issues like browser closes just after test starts and corrupted downloading of jar binaries by wdman but I'll make it work soon.
I'm using R v3.6.3. I'll upgrade to R v4.0.0 with #34 as you said.

**Comment by tdhock** [comment]
what is "corrupted downloading of jar binaries by wdman" ?
why does the browser close just after the test starts?
The browser window should stay open for the entire test suite.

**Comment by lazycipher** [comment]
As RSelenium uses wdman to start selenium server and download the binary in latest version and I wasn't getting much error details in console. So, I tried running `wdman::selenium()` which gave me this error.
```
wdman::selenium()
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
Creating directory: /home/lazycipher/.local/share/binman_seleniumserver/generic/4.0.0-alpha-1
Downloading binary: https://www.googleapis.com/download/storage/v1/b/selenium-release/o/4.0%2Fselenium-server-standalone-4.0.0-alpha-1.jar?generation=1556122...

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```
So, I downloaded and placed working binary manually. And Started server.
```
sel <- wdman::selenium()
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking chromedriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking geckodriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking phantomjs versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
> sel$log()
$stderr
[1] "Error: Invalid or corrupt jarfile /home/lazycipher/.local/share/binman_seleniumserver/generic/4.0.0-alpha-2/selenium-server-standalone-4.0.0-alpha-2.jar"

$stdout
character(0)

> 
```

Apart from that, It looks like some session timeout issue with browser instance and I'm working on it.

**Comment by tdhock** [comment]
if you upgrade to most recent versions of R, RSelenium, selenium, firefox, and it still does not work then you should post an issue and ask for help from the RSelenium devs

**Comment by lazycipher** [comment]
I've upgraded to the latest version of R, RSelenium, Selenium, Firefox but this browser auto close just after the test starts occurring. I'm trying to sort this out as soon as possible.

**Comment by tdhock** [comment]
ok please try to look at the RSelenium docs to see what they recommend. can you please create a simple reproducible example that does not involve animint2, but still illustrates your problem? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by tdhock** [comment]
ok that it good you got it to work, docker can be useful for reproducibility purposes, so please explain what docker container you are using.
also you should be able to get it to work without docker, in theory...

**Comment by lazycipher** [comment]
I'm using [`selenium/standalone-firefox-debug:latest`](https://hub.docker.com/r/selenium/standalone-firefox-debug).
It's working fine most of the times but somehow firefox crashes over there as well. I found an issue opened recently on firefox repo but couldn't find much. [related issue](https://github.com/mozilla/geckodriver/issues/1676)
I'm thinking to analyze the crash report to get to the reason why it's happening and I guess it'll make clear why it's not working properly.

#### `Log of docker:`
```
2020-05-18 16:09:51,774 INFO Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
2020-05-18 16:09:51,774 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2020-05-18 16:09:51,786 INFO supervisord started with pid 7
2020-05-18 16:09:52,792 INFO spawned: 'xvfb' with pid 10
2020-05-18 16:09:52,800 INFO spawned: 'fluxbox' with pid 11
2020-05-18 16:09:52,808 INFO spawned: 'vnc' with pid 12
2020-05-18 16:09:52,823 INFO spawned: 'selenium-standalone' with pid 13
2020-05-18 16:09:53,831 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-05-18 16:09:53,832 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-05-18 16:09:53,833 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-05-18 16:09:53,836 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
16:09:55.518 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
16:09:56.209 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2020-05-18 16:09:56.424:INFO::main: Logging initialized @3382ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:09:57.289 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
16:09:57.616 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
16:11:37.940 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "javascriptEnabled": true,
  "nativeEvents": true,
  "version": ""
}
16:11:37.950 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1589818299138	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilef4gkcT"
1589818301393	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1589818303120	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1589818303120	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1589818303121	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1589818303121	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1589818309239	Marionette	INFO	Listening on port 35857
16:11:49.436 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:11:49.761 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session b2f103a7-ca26-4cd6-9779-51f49f9ebfac (org.openqa.selenium.firefox.GeckoDriverService)
JavaScript error: http://host.docker.internal:4848/animint-htmltest/, line 20: ReferenceError: animint is not defined
JavaScript error: http://host.docker.internal:4848/animint-htmltest/animint.js, line 1536: TypeError: elements.exit is not a function
16:49:04.423 INFO [ActiveSessions$1.onStop] - Removing session b2f103a7-ca26-4cd6-9779-51f49f9ebfac (org.openqa.selenium.firefox.GeckoDriverService)
1589820544435	Marionette	INFO	Stopped listening on port 35857
16:57:17.177 INFO [ActiveSessionFactory.apply] - Capabilities are: {
16:57:17.178 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1589821037228	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilenFEHCb"
1589821038273	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1589821040064	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1589821040065	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1589821040067	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1589821040067	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1589821045991	Marionette	INFO	Listening on port 42231
16:57:26.256 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:57:26.274 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 1d333e05-182f-4597-bc2d-7c6493743093 (org.openqa.selenium.firefox.GeckoDriverService)
JavaScript error: resource://gre/modules/NetworkGeolocationProvider.jsm, line 555: TypeError: xhr.response.location is undefined
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1589821417776	Marionette	INFO	Stopped listening on port 42231
```
#### Screenshare of the issue.[Video](https://www.youtube.com/watch?v=0OUKvNlqBwo)

**Comment by tdhock** [comment]
is this specific to firefox? can you try another browser? what other browsers does selenium/RSelenium support?

**Comment by lazycipher** [comment]
Let me try this with any other browser.

**Comment by lazycipher** [comment]
I've tried on chrome and firefox. I found out that:
- Both get crashed when used [`rsDriver()`](https://www.rdocumentation.org/packages/RSelenium/versions/1.7.7/topics/rsDriver) function.
- None crash when used [`remoteDriver()`](https://www.rdocumentation.org/packages/RSelenium/versions/1.7.7/topics/remoteDriver-class).

Here's the code for both ways.
### Using `rsDriver()`
This function first creates a selenium server using `wdman::selenium()` then starts a browser client.
It's a wrapper upon [`wdman::selenium(`) and `remoteDriver()`](https://github.com/ropensci/RSelenium/blob/31b023293eaffe39f08f17c7abce7fd01a4e2c07/R/rsDriver.R#L73).
```r
rD <- RSelenium::rsDriver(
      remoteServerAddr = "localhost",
      port = 4445L,
      browser = "firefox",
      verbose = TRUE,
      check = TRUE,
    )
remDr <<- rD[['client']]
```

### Using `remoteDriver()` 
This function connects the browser with the server i.e makes the webdriver work.
Since we need a selenium server, I used `wdman::selenium()` to create one.
```r
    selenium <- wdman::selenium(port = 4445L)
    remDr <<- remoteDriver(
      port = 4445L,
      browser="firefox"
    )
```
The second one works perfectly fine. I've tried this many times. I assume the use of `remoteDriver` was the reason the session on docker wasn't crashing

**Comment by tdhock** [comment]
ok thanks for the update. is that with the most recent version of
everything? can you commit/push that fix for the tests to this branch
please? https://github.com/tdhock/animint2/pull/34

**Comment by lazycipher** [comment]
Sure thing!
I'll push it today!

**Comment by lazycipher** [comment]
@tdhock, What's your views on moving testing on docker?
I've faced issues regarding version mismatch and I think docker can be a good option for us. It'll be helpful for new contributors.
What do you say?

**Comment by lazycipher** [comment]
Hi @tdhock, I've pushed the made changes.

**Comment by tdhock** [comment]
moving discussion to #34
