### ISSUE TITLE
gsoc'20 call summary

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint2#38]
TODO post summary of calls.

**Comment by tdhock** [comment]
- push/commit more often (at least once per day).
- send me links to blog post to read.
- currently upgrading testing packages. some issues. clickElement function not working. tried to execute javascript using executeScript works. change implementation of clickID? report as an issue to RSelenium? Minimal reproducible example. double check if the ID is there and only occurs once -- sometimes selenium does not work when there is more than one element with the same ID.
- Rmd rendering? calling the knit print test, it renders the page, but instead of the animations, its just showing what the animint package shows on the console. look in the DOM? can't find the animint.js file? based on output looks like print method is being run, but knit_print should be run, maybe look at knitr / rmarkdown to see if there are any new ways to handle knit_print methods?
```
> methods(knitr::knit_print)
 [1] knit_print.animint                    knit_print.data.frame*               
 [3] knit_print.default*                   knit_print.grouped_df*               
 [5] knit_print.html*                      knit_print.knit_asis*                
 [7] knit_print.knitr_kable*               knit_print.pillar_squeezed_colonnade*
 [9] knit_print.rowwise_df*                knit_print.shiny.tag*                
[11] knit_print.shiny.tag.list*            knit_print.tbl_sql*                  
see '?methods' for accessing help and source code
> 
```
- moving testing to docker? make a blog post or screencast to explain how to do that.

**Comment by lazycipher** [comment]
- Why GSoC?
- Push regularly. The pushed code needs not necessarily to be perfectly working.
- Consolidate `clickHTML` and `clickID` if possible.
- Report dependency issues to the developers with minimal reproducible examples.
- `knit_print.Rmd` rendering due to print method issues.
- Moving tests to docker and write a post about that and if possible make a video.
- OPPs reference with help(gganimintproto) see implementation in geom- files.
- Write every week or every 2 weeks a blog post.

**Comment by tdhock** [comment]
hi @lazycipher would you like another call next week?
if not please mention me in any issues you would like me to help with.

**Comment by lazycipher** [comment]
hi @tdhock, Can we have a call?
I'm having issues in understanding what causes this issue https://travis-ci.org/github/lazycipher/animint2/jobs/702589867#L9147
and a few more things.

**Comment by tdhock** [comment]
to solve that issue just delete that example and then recompile documentation via devtools::document()
```
> d + stat_sum_df("mean_sdl", mapping = aes(group = cyl))
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Error: Aesthetics must be either length 1 or the same as the data (32): x, y
```

**Comment by tdhock** [comment]
next week is really not that great for me for a call so let's try to use github ok?

**Comment by lazycipher** [comment]
@tdhock sounds good to me!
I'll recompile and the push. I missed that part. Hopefully it'll work now.

**Comment by lazycipher** [comment]
Hii @tdhock, Can you check what's this test renders and probably explain this test a bit to me, please?
https://github.com/tdhock/animint2/blob/master/tests/testthat/test-renderer4-Inf.R
![Screenshot from 2020-06-28 21-15-40](https://user-images.githubusercontent.com/17141301/85952286-b794e980-b985-11ea-9bab-3bfdbb3a62db.png)

The test is failing because of line 36.

**Comment by tdhock** [comment]
this test is supposed to make sure that Inf/-Inf are rendered properly on both the x and y axes (at the edge of the panel).
the line number 36 is the following which computes the y position of the bottom of one of the drawn line segments
```
seg.bottom <- as.numeric(attr.mat["y1",])
```

**Comment by lazycipher** [comment]
@tdhock, whenever you get free, I need your help to solve the above issue and #40.

**Comment by tdhock** [comment]
hi what is the above issue? looks like the viz with Inf/-Inf is rendering fine so you just need to make sure the testing code is extracting the positions correctly right?

**Comment by lazycipher** [comment]
If that's the case, then we are looking in the wrong panels for lines.
I'll rectify this asap.

**Comment by lazycipher** [comment]
@tdhock, I don't know why it's happening! https://github.com/lazycipher/animint2/commit/78c853598c6ad21eebec91b8e3fcceda1689b1ca
The whole file is being taken as modified while when I commit, I check and I see only a single line being modified!

**Comment by lazycipher** [comment]
The graph isn't rendering properly!
On R v4:
![Screenshot from 2020-07-09 13-42-35](https://user-images.githubusercontent.com/17141301/87014805-460d3480-c1ea-11ea-854b-ff863d5ae0ba.png)

While on R v3.6.3:
![Screenshot from 2020-07-09 13-42-29](https://user-images.githubusercontent.com/17141301/87014866-5ae9c800-c1ea-11ea-984f-e5a4f4254701.png)

We can clearly see that the plotted graph seems 90 degrees tilted! It's some calculation issue. I'll get it working by today anyhow.

**Comment by lazycipher** [comment]
Fixed this! It was `stringsAsFactors = TRUE` that was missing!

**Comment by tdhock** [comment]
great, that makes sense.

**Comment by lazycipher** [comment]
Hi @tdhock, @faizan-khan-iit, I'm having issues in getting the flow of data.
If possible can we have a call as soon as possible please so that I can proceed with #43?

I've also made and posted 2 videos of testing on [YouTube](https://www.youtube.com/channel/UCmq-HuPibUBezW35oeUSC-Q) which shows how it's done on Linux and Windows. Soon I'll be posting a few videos in which I'll be making animated viz.

**Comment by lazycipher** [comment]
Call on 29th July with @faizan-khan-iit,
- Everything looks good till now: @faizan-khan-iit.
- I'm working on OOPs implementation. Things look quite good as of now. We should wait for @tdhock for his thoughts over the current implementation.
- A discussion about possible ways to make it work.
- Is it feasible to compute all required data from inside the `geom_*` functions? 
- Once done with current OOPs implementation, we should go ahead with moving the calculation of subset
from compiler to renderer.

@faizan-khan-iit, Please let me know if I missed anything.

Thank you so much for the detailed discussion.

**Comment by tdhock** [comment]
problem understand what is R package? no, problem understanding how R package works. that is normal.
details about problems?
move geom pre-processing to specific geom classes. issue is how? move common processing to base geom, then move geom-specific code to specific classes. sounds great, reasonable.
in base Geom class, you have the save/export method, then from within that method, you call the pre_process method. If `l` is the layer object then you call `l$pre_process()`. in base Geom class you need a pre_process method that is a no-op.
How do you get the modified data back? save the return value?
