### ISSUE TITLE
too much space between each plot and its title

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint2#40]
@lazycipher I noticed a new bug/regression. can you please add a test and work on a fix in #34 ?
In old animint2 which worked with R-3.6 we have very little space between each plot and its title:

![screenshot-old-animint2-R-3 6](https://user-images.githubusercontent.com/932850/84531601-aff0f780-ac99-11ea-9ab9-06080791a44f.png)

but in new animint2 we have

![screenshot-too-much-space-animint2-R-4 0](https://user-images.githubusercontent.com/932850/84531664-c9923f00-ac99-11ea-9afe-90d546065141.png)

the problem seems to be with the offset of the plot which is 111 here in the background y attribute

![plot-offset-too-big-animint2](https://user-images.githubusercontent.com/932850/84531741-e2025980-ac99-11ea-9f91-dd94cc89b027.png)

this is the first plot in test-renderer2-interactive-legends.R but this is happening with ALL animints I have seen with the new code.

**Comment by lazycipher** [comment]
Sure @tdhock, I'll work around this issue and report back as soon as possible.

**Comment by tdhock** [comment]
hi what do you need help with here? can you replicate the issue / see the problem in rendered data viz on your system?

**Comment by lazycipher** [comment]
Yes, my system also has the same issue.
Can you guide me on where should I look for in order to solve this issue?
I noticed that the title was using a css property, `transform: translate(200, 17)`, which looked responsible for this issue.

**Comment by tdhock** [comment]
yes maybe that it is. try experimenting with changing those translate values interactively in the browser to see if that fixes the problem. then if it does, figure out where those values are being generated in the R/js code.

**Comment by lazycipher** [comment]
This line is causing issues! https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/inst/htmljs/animint.js#L515
It renders correctly on R 3.6 but not on R 4.0. I guess it might be something related to some unit implementation.
I haven't found the R code responsible for passing these values but I'm sure I'll find this soon.

**Comment by tdhock** [comment]
thanks for your persistence/dilgence.
plotdim.margin comes from
```js
    var margin = {
      left: 0,
      right: text_height_pixels * p_info.panel_margin_lines,
      top: text_height_pixels * p_info.panel_margin_lines,
      bottom: 0
    };
```
which comes from the following R code inside parsePlot:
```r
  ## Now ggplot specifies panel.margin in 'pt' instead of 'lines'
  plot.info$panel_margin_lines <- pt.to.lines(theme.pars$panel.margin)
```

**Comment by lazycipher** [comment]
The value of `theme.pars$panel.margin` is `5.5pt` in 3.6 while the value is `5.5points` in 4.0.
The function `pt.to.lines` is not working as expected in 4.0.

**Comment by lazycipher** [comment]
Thank you so much!
The value of `theme.pars$panel.margin` is `5.5pt` in 3.6 while the value is `5.5points` in 4.0.
The function `pt.to.lines` is not working as expected in 4.0.

**Comment by lazycipher** [comment]
It was the function `pt.to.lines()` which was having issues. Actually the issue was caused as we were trying to extract unit type by using `attributes(pt_value)$unit`. In the new grid, there's a new function `unitType()` to extract that.


> several packages were extracting attributes from “unit” objects, e.g., the "mm" from unit(1, "mm"); there is a new grid::unitType() function that may help packages to avoid accessing ‘grid’ unit internals in the future.
ref: https://developer.r-project.org/Blog/public/2020/04/13/changes-to-grid-units/index.html

**Comment by tdhock** [comment]
did you add a test that fails before your fix? if not can you do that please? (always a good idea to write a test that fails when you find a bug, before you fix the bug)

**Comment by lazycipher** [comment]
Oh! I'm sorry! I forgot!
I'll add this asap.

**Comment by lazycipher** [comment]
@tdhock, One thing I have to ask, this test will be a renderer one or what?
Calculating distance between title and plot is easy but with what we'll be comparing to make sure it's not big enough!

**Comment by tdhock** [comment]
you are right the renderer test is not super easy / straightforward.
anyway the bug was with the compiler (r code) so you should probably just test pt.to.lines, or test the panel_margin_lines attribute of the compiled viz list, see other test-compiler* files.

**Comment by lazycipher** [comment]
Alright! Let me go ahead!
