### ISSUE TITLE
Object Oriented implementation of geoms

### ISSUE THREAD

**Issue by lazycipher** [tdhock/animint2#43]
Currently, the [`saveLayer`](https://github.com/tdhock/animint2/blob/c2398111e8b0e73e73fac28a8d56d8cf3a912a4c/R/z_animint.R#L200) function uses many if-else conditions.
The idea is to make sayLayer a base class and move all the conditional check codes to geom specific files for better understandability and maintainability.
As per @faizan-khan-iit, 

> In animint, especially for data pre-processing, we use lots of geom specific code, we need to transfer that code to the geom definition. Let's say we introduce a new function in the code (like 'translate_shape_string' in geom_point above) which does this task, we will be able to process that data when the geom is being built and we won't need those if-else statements anymore.

**Comment by faizan-khan-iit** [comment]
One possible implementation that makes sense to me would be this:
1. Move all the code that is common to the geoms to the geom base file. This function will be behave the same no matter which geom is being used.
1. As for the if-else blocks, we will have separate implementations of these as per the geom requirements (which you can just copy/paste from the saveLayer function) for each geom. These would be present in the geom-*.R files.

There can be two ways of invoking this. You can define it in the geom files and invoke them in the saveLayer function (like creating a separate class in normal OOPs and invoking using an instance). Or you can invoke it in the geom itself when other geom specific stuff is happening (kind of like `draw_panel` in ggplot2).

@tdhock Toby do you have any suggestions on any other approach which might work better here?

**Comment by lazycipher** [comment]
@faizan-khan-iit, Please let me know if I'm going in right direction!
https://github.com/lazycipher/animint2/commit/6e52f81235015848b0a1e07f958f917218529c4f

**Comment by faizan-khan-iit** [comment]
@lazycipher This looks like a good change. One thing I would like to happen is for the data to be converted automatically in the geom definition. Can you do that instead? That way we can just get rid of the if-else blocks completely and have much cleaner code!

**Comment by lazycipher** [comment]
Alright! I'll move that way! I'm having issues in understanding the current workflow hence it's taking time for me to get it working.
I'll do my best to complete it asap.

**Comment by tdhock** [comment]
agree with Faizan, all geom specific data conversions should happen in geom methods, so we can avoid if-else

**Comment by lazycipher** [comment]
This issue closes with #45
