### ISSUE TITLE
Package ‘ggplot2Animint’ is not available for this version of R

### ISSUE THREAD

**Issue by damodardhakad** [tdhock/animint2#51]
Few examples like [Climate.R](https://github.com/tdhock/animint2/blob/master/inst/examples/Climate.R) require ggplot2Animint library. I have tried installing that but it seems this package is not available on CRAN. Where should I find it?

R version -  4.0.4 (2021-02-15)

**Comment by AmolGirishShah** [comment]
The ggplot2Animint library has been integrated within the animint2 library itself, hence there is no CRAN package for it. If you want to absolutely make it work, you can install it from here
```
# install.packages("devtools")
devtools::install_github("faizan-khan-iit/ggplot2@e62066b462070a3a46f403d6f63531413a3a20ce")
```
Source: from https://github.com/faizan-khan-iit/ggplot2/tree/cran

**Comment by damodardhakad** [comment]
Thanks, @AmolGirishShah!
