### ISSUE TITLE
fix test warnings

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint2#56]
hey @faye-yufan tests on GH actions CI are currently passing but have lots of warnings, for example in https://github.com/tdhock/animint2/runs/6580075868?check_suite_focus=true
```
── Warning (test-renderer1-facet-lines.R:50:1): (code run outside of `test_that()`) ──
to ensure that smooth transitions are interpretable, aes(key) should be specifed for geoms with showSelected=year, problem: geom6_text_ts
Backtrace:
 1. animint2:::animint2HTML(wb.facets)
      at test-renderer1-facet-lines.R:50:0
 2. animint2::animint2dir(...)
      at tests/testthat/helper-HTML.R:5:2
 3. animint2:::issueSelectorWarnings(...)
── Warning (test-renderer1-facet-space.R:35:5): some horizontal space between panels ──
Deprecated: please use `expect_lt()` instead
Backtrace:
 1. testthat::expect_less_than(first.right, second.left)
      at test-renderer1-facet-space.R:35:4
```
It would be nice to fix the tests so that these warnings disappear. This would be a good first issue/PR for you to work on during the next week or so (because it is such a simple fix), in order for you to get familiar with the process of creating a new branch/PR and then requesting code review from @Csaluski

**Comment by tdhock** [comment]
To fix `to ensure that smooth transitions are interpretable, aes(key) should be specifed` you should add `aes(key=something)` to the ggplot code in the test (something may be different for every test case though).
To fix `Deprecated: please use `expect_lt()` instead` you can just change all `expect_less_than` to `expect_lt` in the test code.

**Comment by Faye-yufan** [comment]
It seems some ```aes(key)```warnings were caused by ```make_test()``` functions, since when I substitute ```make_text(WorldBank, 55, 9, "year")```  with ```geom_text(aes(5, 85, label=paste0("year = ", year), key=year), showSelected="year", data=WorldBank)``` the warning would disappear. So shall I keep the ```make_test()``` function?

**Comment by tdhock** [comment]
`make_text()` should not create any warnings, so instead of changing to `geom_text` we should change the definition of `make_text`.
