### ISSUE TITLE
User configurable alpha for selected and deselected elements

### ISSUE THREAD

**Issue by csaluski** [tdhock/animint2#59]
Currently Animint's alpha system is very simple and works by taking a base alpha value for a geometry, either in its geometry attributes as the alpha for every element in the geometry, or as an aes parameter so that points can have an alpha determined by their value. When the element is selected it uses the full alpha value, and when it is deselected it uses that alpha value minus 0.5.

I believe a very straightforward approach for this feature would be to add a new aes property that is recognized by the Javascript rendering code, which when an element is deselected it would get the new alpha from a `alpha_off` property if it exists, or default to the original alpha - 0.5 if it does not exist. This would preserve compatibility with existing plot systems and would only require changes in [a small section of code](https://github.com/tdhock/animint2/blob/96ec0caf446c555ae847febdf3681de6a6525ee8/inst/htmljs/animint.js#L1570-L1581), as Animint's compiler will already put arbitrary aesthetic and geometry attributes into its output `plot.json` and `geom_*.tsv` files. 

Another, much more involved, idea I had relating to this is the idea of having an entirely separate secondary geometry and aesthetic for `clickSelects` geometry. This would allow for enhanced visual clarity, such as by selected geometry being a highlight color instead of just higher opacity. 

I'd appreciate feedback on both of these ideas, and I believe I could have the `alpha_off` property working within a day or two if that's the approach we decide on.

**Comment by tdhock** [comment]
I think that is a great idea to allow aesthetics other than alpha, like color_off, size_off, etc.
good to start with alpha_off.
